const dishes = [
  {
    id: 1,
    name: "Spicy Dragon Noodles",
    duration: "30",
    rating: 4.7,
    price: "15.99",
    type: "trending",
    popular: 9.0,
    category: "asian",
    image: "http://localhost:7777/images/dishes/SpicyDragonNoodles.webp",
  },
  {
    id: 2,
    name: "Golden Turmeric Rice",
    duration: "25",
    rating: 4.5,
    price: "10.99",
    type: "healthy",
    popular: 8.5,
    category: "asian",
    image: "http://localhost:7777/images/dishes/GoldenTurmericRice.webp",
  },
  {
    id: 3,
    name: "Classic Pepperoni Pizza",
    duration: "20",
    rating: 4.8,
    price: "12.99",
    type: "supreme",
    popular: 9.2,
    category: "pizza",
    image: "http://localhost:7777/images/dishes/ClassicPepperoniPizza.webp",
  },
  {
    id: 4,
    name: "Veggie Pizza",
    duration: "15",
    rating: 4.2,
    price: "11.99",
    type: "healthy",
    popular: 8.0,
    category: "pizza",
    image: "http://localhost:7777/images/dishes/VeggiePizza.webp",
  },
  {
    id: 5,
    name: "Chocolate Donut",
    duration: "10",
    rating: 4.9,
    price: "2.99",
    type: "trending",
    popular: 9.5,
    category: "donut",
    image: "http://localhost:7777/images/dishes/ChocolateDonut.webp",
  },
  {
    id: 6,
    name: "Glazed Donut",
    duration: "12",
    rating: 4.7,
    price: "1.99",
    type: "trending",
    popular: 9.1,
    category: "donut",
    image: "http://localhost:7777/images/dishes/GlazedDonut.webp",
  },
  {
    id: 7,
    name: "Ice Cream Sundae",
    duration: "5",
    rating: 4.5,
    price: "3.99",
    type: "supreme",
    popular: 9.8,
    category: "ice",
    image: "http://localhost:7777/images/dishes/IceCreamSundae.webp",
  },
  {
    id: 8,
    name: "Frozen Yogurt",
    duration: "7",
    rating: 4.0,
    price: "4.50",
    type: "healthy",
    popular: 8.4,
    category: "ice",
    image: "http://localhost:7777/images/dishes/FrozenYogurt.webp",
  },

  {
    id: 9,
    name: "Mango Sticky Rice",
    duration: "20",
    rating: 4.9,
    price: "7.99",
    type: "trending",
    popular: 8.9,
    category: "asian",
    image: "http://localhost:7777/images/dishes/MangoStickyRice.webp",
  },
  {
    id: 10,
    name: "Teriyaki Chicken",
    duration: "25",
    rating: 4.8,
    price: "12.50",
    type: "supreme",
    popular: 9.3,
    category: "asian",
    image: "http://localhost:7777/images/dishes/TeriyakiChicken.webp",
  },
  {
    id: 11,
    name: "BBQ Chicken Pizza",
    duration: "22",
    rating: 4.7,
    price: "13.99",
    type: "trending",
    popular: 8.8,
    category: "pizza",
    image: "http://localhost:7777/images/dishes/BBQChickenPizza.webp",
  },
  {
    id: 12,
    name: "Seafood Pizza",
    duration: "24",
    rating: 4.5,
    price: "15.99",
    type: "healthy",
    popular: 8.6,
    category: "pizza",
    image: "http://localhost:7777/images/dishes/SeafoodPizza.webp",
  },
  {
    id: 13,
    name: "Caramel Donut",
    duration: "15",
    rating: 4.6,
    price: "2.49",
    type: "supreme",
    popular: 9.2,
    category: "donut",
    image: "http://localhost:7777/images/dishes/CaramelDonut.webp",
  },
  {
    id: 14,
    name: "Matcha Donut",
    duration: "18",
    rating: 4.4,
    price: "2.99",
    type: "healthy",
    popular: 8.7,
    category: "donut",
    image: "http://localhost:7777/images/dishes/MatchaDonut.webp",
  },
  {
    id: 15,
    name: "Raspberry Sorbet",
    duration: "10",
    rating: 4.9,
    price: "4.99",
    type: "healthy",
    popular: 9.1,
    category: "ice",
    image: "http://localhost:7777/images/dishes/RaspberrySorbet.webp",
  },
  {
    id: 16,
    name: "Chocolate Ice Cream",
    duration: "8",
    rating: 5.0,
    price: "3.50",
    type: "trending",
    popular: 9.5,
    category: "ice",
    image: "http://localhost:7777/images/dishes/ChocolateIceCream.webp",
  },
];

module.exports = dishes;
